### ISSUE TITLE
Playback Crashes Web App - Amazon Fire TV Stick

### ISSUE THREAD

**Issue by seftonmonk** [fmtvp/talexample#27]
Hi,

I have checked out your example application and got it running on a amazon fire tv stick pointing to the correct configuration file.

When i go to play a video, the amazon web app crashes with no stack trace, have you guys experienced this, same app works on chrome perfectly.

Any help would be appreciated.

Cheers,
Sefton

**Comment by tsadler1988** [comment]
Hi Sefton,

Are you using the normal web browser or a web view in a native app?

Tom

**Comment by tsadler1988** [comment]
Hi Sefton,

We're going to close this as we haven't heard from you.

For future reference, I believe the Amazon Fire TV/TV Stick devices have different ways of launching browsers (hence my question about web view vs normal web browser) and my theory about this problem is that a browser without proper HTML5 media support has been launched somehow.

Tom
